// Generated by CoffeeScript 1.7.1
var compiler, emblem;

emblem = require('emblem');

compiler = require('ember-template-compiler');

module.exports = function(content) {
  var compiled;
  this.cacheable && this.cacheable();
  compiled = Emblem.precompile(compiler.EmberHandlebars, content, {
    simple: true
  });
  return "module.exports = Ember.Handlebars.template(" + compiled + ");";
};
